### ISSUE TITLE
Python client dies if no dictionary selected

### ISSUE THREAD

**Issue by recrudesce** [s3inlc/hashtopolis#325]
Your current Server version located at the bottom of any hashtopussy webpage.
0.5.0alpha

Current Client version
Python latest from repos

Your current Hashcat version
4.0.1

When creating a task, if you forget to select a wordlist, the Python client will crash out because the hashcat binary returns an error.  This is mostly due to lack of concentration on the user's part, however.

```
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 238
b'{"action":"getTask","response":"SUCCESS","taskId":18,"attackcmd":"#HL#  -O -p ] --hash-type=13100 ","cmdpars":"","hashlistId":8,"bench":30,"statustimer":5,"files":[],"crackerId":"1","benchType":"run","hashlistAlias":"#HL#","keyspace":"0"}'
Got task with id: 18
{'binaryVersionId': '1', 'type': 'cracker', 'action': 'downloadBinary', 'token': 'P47pEZe4Ib'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 149
b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/hashcat.net\\/files\\/hashcat-4.0.1.7z","name":"hashcat","executable":"hashcat64.bin"}'
{'hashlistId': 8, 'action': 'getHashlist', 'token': 'P47pEZe4Ib'}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 98
b'{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=8&token=P47pEZe4Ib"}'
Starting new HTTP connection (1): 10.35.3.125
"HEAD /getHashlist.php?hashlists=8&token=P47pEZe4Ib HTTP/1.1" 200 0
Starting new HTTP connection (1): 10.35.3.125
"GET /getHashlist.php?hashlists=8&token=P47pEZe4Ib HTTP/1.1" 200 1313
Downloading: [====================================================================================]
Got cracker binary type hashcat
{'token': 'P47pEZe4Ib', 'action': 'getChunk', 'taskId': 18}
Starting new HTTP connection (1): 10.35.3.125
"POST /api/server.php HTTP/1.1" 200 71
b'{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}'
Traceback (most recent call last):
  File "./__main__.py", line 122, in <module>
    loop()
  File "./__main__.py", line 86, in loop
    cracker.measure_keyspace(task.get_task(), chunk)
  File "/opt/htp_python2/htpclient/hashcat_cracker.py", line 154, in measure_keyspace
    output = subprocess.check_output(full_cmd, shell=True, cwd='files')
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '../crackers/1/hashcat64.bin --keyspace --quiet  -O -p ] --hash-type=13100 ' returned non-zero exit status 255
```

**Comment by s3inlc** [comment]
The client should not crash anymore on this error. It should report a keyspace measure error to the server and then continue with getting tasks from the server.

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
