### ISSUE TITLE
Fatal error on upgrade 0.4.3 -> 0.5.0

### ISSUE THREAD

**Issue by Thireus** [s3inlc/hashtopolis#414]
- Your current Server version located at the bottom of any Hashtopolis webpage: 0.4.3

- The exact task command you are trying to run:

`php -f install/updates/update_v0.4.0_v0.5.0.php`

- Debug output:

```
# php -f install/updates/update_v0.4.0_v0.5.0.php
WARNING!!!!
This update contains some drastic changes and everything except users, agents, files, hashlists, pretasks and supertasks will not be kept!
Backup the database before applying this update, in case something does not run as expected!
Do this upgrade ONLY if you really don't want to do a clean installation instead!
NOTE: If you have a lot of hashes imported, make sure that this process gets enough ram assigned!
Enter 'AGREE' to continue...
AGREE
Apply updates...
Disable checks... OK
Read Config table... OK
Read users... OK
Read agents... OK
Read files... OK
Read taskFile... OK
Read hashlists... OK
Read superhashlists... OK
Read hashes... OK
Read binary hashes... OK
Read tasks... OK
Read supertasks... OK
Read supertaskTasks... OK
Read hash types... OK
All data loaded! Removing old tables... OK
Importing new scheme... OK
Reload full include... (Warning about sessions might show up, which can be ignored)PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php:24) in /var/www/hashtopussy/inc/load.php on line 8
PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php:24) in /var/www/hashtopussy/inc/load.php on line 8
OK
Starting with refilling data...
Create default access group... OK
Add Hashcat to CrackerBinaryType table... OK
Save hash types... OK
Save users... PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`hashtopussy`.`User`, CONSTRAINT `User_ibfk_1` FOREIGN KEY (`rightGroupId`) REFERENCES `RightGroup` (`rightGroupId`)) in /var/www/hashtopussy/dba/AbstractModelFactory.class.php:267
Stack trace:
#0 /var/www/hashtopussy/dba/AbstractModelFactory.class.php(267): PDOStatement->execute(Array)
#1 /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php(167): DBA\AbstractModelFactory->massSave(Array)
#2 {main}
  thrown in /var/www/hashtopussy/dba/AbstractModelFactory.class.php on line 267
```

OS:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=17.10
> DISTRIB_CODENAME=artful
> DISTRIB_DESCRIPTION="Ubuntu 17.10"

> Linux HTP 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PHP:

> PHP 7.1.17-0ubuntu0.17.10.1 (cli) (built: May  9 2018 17:28:01) ( NTS )

**Comment by s3inlc** [comment]
Did you have custom Permission Groups or did you ever deleted/added such groups?

**Comment by Thireus** [comment]
Yes, I have several groups setup. Should I remove them before the upgrade?

**Comment by s3inlc** [comment]
Ok, these are causing the problems because after the upgrade these groups are overwritten by the default ones and the association of the users to the groups fails because the IDs don't match.

Just removing them wouldn't solve it, you would have to assign all users to a group which existed from the original setup. If you don't mind loosing the association of the users to the groups (you still could apply afterwards), you can do this. 
Otherwise I would have to extend the upgrade script a bit to also take over the groups.

**Comment by winxp5421** [comment]
Closing this. If you are still having issues please re open
