### ISSUE TITLE
client.log runs out of disk space and kills the agent

### ISSUE THREAD

**Issue by tosiara** [s3inlc/hashtopolis#667]
- Current Client version: `s3-python-0.6.0.10`
- Your current Hashcat version: `0.12.0 commit 0e9047b`
- Agent's OS: Ubuntu 18

I have encountered another way when an agent may die - when system runs out of disk space

In my case I had `client.log` almost 5GB, deleting it and restarting solved the issue. But, probably, implementing a limit for log file or file rotation would be better.

Relevant exception call stack:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "hashtopolis.zip/__main__.py", line 343, in <module>
    loop()
  File "hashtopolis.zip/__main__.py", line 162, in loop
    task.load_task()
  File "hashtopolis.zip/htpclient/task.py", line 35, in load_task
    logging.info("No task available!")
Message: 'No task available!'
Arguments: ()
No task available!
```

**Comment by s3inlc** [comment]
Agreed, 5GB seems to be quite big. With debug enabled it produces quite some output.
I will put it on the list and will implement something that it separates by day/month and cleans up old files.
