### ISSUE TITLE
Integrity constraint violation column userId cannot be null during install

### ISSUE THREAD

**Issue by hirodotp** [s3inlc/hashtopolis#673]
Using release 0.12.0 (tried both tag from git repo and the stand alone release).
PHP 7.3
Apache 2.4.34

Receiving the following error when submitting the form to create the admin user account:

Here is the backtrace from the apache log:

`PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userId' cannot be null in /home/skullbox.io/htdocs/public/hashtopolis/dba/AbstractModelFactory.class.php:114\nStack trace:\n#0 /home/skullbox.io/htdocs/public/hashtopolis/dba/AbstractModelFactory.class.php(114): PDOStatement->execute(Array)\n#1 /home/skullbox.io/htdocs/public/hashtopolis/dba/models/UserFactory.class.php(80): DBA\\AbstractModelFactory->save(Object(DBA\\User))\n#2 /home/skullbox.io/htdocs/public/hashtopolis/install/index.php(184): DBA\\UserFactory->save(Object(DBA\\User))\n#3 {main}\n  thrown in /home/skullbox.io/htdocs/public/hashtopolis/dba/AbstractModelFactory.class.php on line 114`

**Comment by hirodotp** [comment]
Related to database version issue and settings.  sql dump failed to apply but was unable to see error message in web console, this may be something ot address in the future.
